[profile.default]
src = "contracts1"
out = "artifacts"
libs = ["node_modules", "lib"]
remappings = [
    "@chainlink/=node_modules/@chainlink/",
    "@eth-optimism/=node_modules/@chainlink/contracts/node_modules/@eth-optimism/",
    "@morpho-org/=node_modules/@morpho-org/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@scroll-tech/=node_modules/@scroll-tech/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
    "forge-std/=lib/forge-std/src/",
]
gas_reports = ["*"]

optimizer = true
optimizer_runs = 200
viaIR = true
fs_permissions = [{ access = "write", path = "./output/deployedContracts.json"}, { access = "write", path = "./output/deployedVault.json"}] 

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
flow="${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
flow={ key = "${ETHERSCAN_API_KEY}"}